### PR TITLE
minor fix

### PR DESCRIPTION
**Pull request by chakrabandla**
Based on condition mentioned in line #35

### CODE REVIEW

**Review by cschlaffner — APPROVED** [review]
Thanks for spotting this error.

**Comment by chakrabandla** [comment]
Thanks for accepting the PR.
Just curious, should "m_count_peptides_phs = 0"  & "m_tissueindex = 0" be added to "MappedPeptides::remove_all_peptides()"

**Comment by cschlaffner** [comment]
You are correct. They should be added to prevent index out of bounds errors.

**Comment by ypriverol** [comment]
@chakrabandla do a PR to solve the issue.

**Comment by chakrabandla** [comment]
@ypriverol yeah,  I already created https://github.com/cschlaffner/PoGo/pull/17

**Pull request merged**
